name: ETL CSV to Azure SQL

on:
  workflow_dispatch: # 手動トリガー可能
  schedule:
    - cron: "0 3 * * 1" # 毎週月曜 3:00 UTC（例：日本時間12:00になるように調整）

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install ODBC Driver for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run ETL script
        env:
          ST_URL: ${{ secrets.ST_URL }}
          SAS_TOKEN: ${{ secrets.SAS_TOKEN }}
          SQL_URI: ${{ secrets.SQL_URI }}
          BLOB_PATH: ${{ secrets.BLOB_PATH }}
        run: python scripts/etl.py
